language: rust
dist: trusty
sudo: required
services:
  - docker
rust:
  - stable
cache: cargo
before_deploy:
  - cargo build --release
  - docker build . -t "edalen/ecs-run:${TRAVIS_TAG}"
  - docker tag "edalen/ecs-run:${TRAVIS_TAG}" "edalen/ecs-run:latest"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  - provider: script
    script: docker push "edalen/ecs-run:${TRAVIS_TAG}" && docker push "edalen/ecs-run:latest"
    on:
      repo: dalen/ecs-run
      tags: true
